apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-api
  labels:
    app: main-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-api
  template:
    metadata:
      name: main-api
      labels:
        app: main-api
    spec:
      containers:
        - name: api
          image: ghcr.io/zgamelogic/main-api:master
          imagePullPolicy: Always
          volumeMounts:
            - name: keystore-volume
              mountPath: "/etc/keystore"
              readOnly: true
            - name: frontend-files-volume
              mountPath: "/front-end"
              readOnly: true
            - name: downloads-volume
              mountPath: "/downloads"
              readOnly: true
          env:
            - name: TZ
              value: "America/Chicago"
          readinessProbe:
            httpGet:
              path: /health
              port: 8085
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8085
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 30
      volumes:
        - name: keystore-volume
          secret:
            secretName: ssl-keystore-secret
        - name: frontend-files-volume
          hostPath:
            path: /home/Ben/front-end/website
            type: Directory
        - name: downloads-volume
          hostPath:
            path: /home/Ben/front-end/downloads
            type: Directory
      restartPolicy: Always
      imagePullSecrets:
        - name: ghcr-secret