### GET a list of repositories when creating a dashboard project
GET localhost:8080/api/dashboard/github-repositories

### Get projects
GET localhost:8080/api/dashboard/projects

### Get Rich projects
GET localhost:8080/api/dashboard/projects/rich

### Create a project
POST https://zgamelogic.com/api/dashboard/projects
Content-Type: application/json

{
  "name": "Spring Boot Starter Discord",
  "description": "A maven library to easily integrate Discord bots (using JDA) into Spring Boot applications.",
  "aspects": ["Spring", "Maven"],
  "githubRepoIds": [753361694]
}