### GET a list of repositories when creating a dashboard project
GET localhost:8080/api/dashboard/github-repositories

### Get projects
GET localhost:8080/api/dashboard/projects

### Get Rich projects
GET localhost:8080/api/dashboard/projects/rich

### Create a project
POST https://zgamelogic.com/api/dashboard/projects
Content-Type: application/json

{
  "name": "Cobble",
  "description": "A fun game project that allows users to build towns and defend them.",
  "aspects": ["Spring", "Kubernetes"],
  "githubRepoIds": [1008634134,1008725971]
}