name: Docker Image CI

on:
  push:
jobs:
  disable-monitor:
    runs-on: ubuntu-latest
    steps:
      - name: disable monitor
        uses: ZGameLogic/data-otter-monitor-active@v1.0.0
        with:
          monitorId: 1
          active: false